=== markfinal/BuildAMation/Bam.Core/Schema/BamPackageDefinitionV1.xsd
<?xml version="1.0" encoding="utf-8" ?>
<xs:schema
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
    targetNamespace="http://www.buildamation.com"
    xmlns="http://www.buildamation.com"
    elementFormDefault="qualified">

<xs:complexType name="bam-assemblies-type">
    <xs:sequence>
        <xs:element name="BamAssembly" minOccurs="1" maxOccurs="unbounded">
            <xs:complexType>
                <xs:attribute name="name" type="xs:string" use="required" />
                <xs:attribute name="major" type="xs:positiveInteger" use="optional" />
                <xs:attribute name="minor" type="xs:nonNegativeInteger" use="optional" />
                <xs:attribute name="patch" type="xs:nonNegativeInteger" use="optional" />
            </xs:complexType>
        </xs:element>
    </xs:sequence>
</xs:complexType>

<xs:complexType name="dotnet-assemblies-type">
    <xs:sequence>
        <xs:element name="DotNetAssembly" minOccurs="1" maxOccurs="unbounded">
            <xs:complexType>
                <xs:attribute name="name" type="xs:string" use="required" />
                <xs:attribute name="requiredTargetFramework" type="xs:string" use="optional" />
            </xs:complexType>
        </xs:element>
    </xs:sequence>
</xs:complexType>

<xs:complexType name="definitions-type">
    <xs:sequence>
        <xs:element name="Definition" minOccurs="1" maxOccurs="unbounded">
            <xs:complexType>
                <xs:attribute name="name" type="xs:string" use="required" />
            </xs:complexType>
        </xs:element>
    </xs:sequence>
</xs:complexType>

<xs:simpleType name="platform-type">
  <xs:restriction base="xs:string">
    <xs:enumeration value="Windows" />
    <xs:enumeration value="Linux" />
    <xs:enumeration value="OSX" />
  </xs:restriction>
</xs:simpleType>

<xs:complexType name="supported-platforms-type">
    <xs:sequence>
        <xs:element name="Platform" minOccurs="1" maxOccurs="unbounded">
            <xs:complexType>
                <xs:attribute name="name" type="platform-type" use="required" />
            </xs:complexType>
        </xs:element>
    </xs:sequence>
</xs:complexType>

<xs:complexType name="package-repository-type">
    <xs:choice minOccurs="1" maxOccurs="unbounded">
        <xs:element name="Repo">
            <xs:complexType>
                <xs:attribute name="dir" type="xs:string" use="required" />
            </xs:complexType>
        </xs:element>
        <xs:element name="NamedRepo">
            <xs:complexType>
              <xs:attribute name="name" type="xs:string" use="required" />
            </xs:complexType>
        </xs:element>
    </xs:choice>
</xs:complexType>

<xs:attributeGroup name="package-attributes">
  <xs:attribute name="name" type="xs:string" use="required" />
  <xs:attribute name="version" type="xs:string" use="optional" />
  <xs:attribute name="default" type="xs:boolean" use="optional" />
</xs:attributeGroup>

<xs:complexType name="package-package-type">
  <xs:attributeGroup ref="package-attributes" />
</xs:complexType>

<xs:complexType name="dependents-type">
  <xs:sequence>
    <xs:element name="Package" minOccurs="1" maxOccurs="unbounded" type="package-package-type" />
  </xs:sequence>
</xs:complexType>

<xs:complexType name="nuget-packages-type">
  <xs:sequence>
    <xs:element name="NuGetPackage" minOccurs="1" maxOccurs="unbounded">
      <xs:complexType>
        <xs:sequence>
          <xs:element name="Platform" minOccurs="1" maxOccurs="unbounded">
            <xs:complexType>
              <xs:attribute name="name" type="platform-type" use="required" />
            </xs:complexType>
          </xs:element>
        </xs:sequence>
        <xs:attribute name="id" type="xs:string" use="required" />
        <xs:attribute name="version" type="xs:string" use="required" />
      </xs:complexType>
    </xs:element>
  </xs:sequence>
</xs:complexType>

<xs:simpleType name="source-valid-type">
  <xs:restriction base="xs:string">
    <xs:enumeration value="http" />
  </xs:restriction>
</xs:simpleType>

<xs:complexType name="sources-type">
  <xs:sequence>
    <xs:element name="Source" minOccurs="1" maxOccurs="unbounded">
      <xs:complexType>
        <xs:attribute name="type" type="source-valid-type" use="required" />
        <xs:attribute name="path" type="xs:anyURI" use="required" />
        <xs:attribute name="subdir" type="xs:string" use="optional" />
        <xs:attribute name="platform" type="platform-type" use="optional" />
      </xs:complexType>
    </xs:element>
  </xs:sequence>
  <xs:attribute name="extractto" type="xs:string" use="optional" />
</xs:complexType>

<!-- root node -->
<xs:element name="PackageDefinition">
    <xs:complexType>
        <xs:all>
            <xs:element name="Description" type="xs:string" minOccurs="0" maxOccurs="1" />
            <xs:element name="Dependents" type="dependents-type" minOccurs="0" maxOccurs="1" />
            <xs:element name="PackageRepositories" type="package-repository-type" minOccurs="0" maxOccurs="1" />
            <xs:element name="BamAssemblies" type="bam-assemblies-type" minOccurs="0" maxOccurs="1" />
            <xs:element name="DotNetAssemblies" type="dotnet-assemblies-type" minOccurs="0" maxOccurs="1" />
            <xs:element name="SupportedPlatforms" type="supported-platforms-type" minOccurs="0" maxOccurs="1" />
            <xs:element name="Definitions" type="definitions-type" minOccurs="0" maxOccurs="1" />
            <xs:element name="NuGetPackages" type="nuget-packages-type" minOccurs="0" maxOccurs="1" />
            <xs:element name="Sources" type="sources-type" minOccurs="0" maxOccurs="1" />
        </xs:all>
        <xs:attribute name="name" type="xs:string" use="required" />
        <xs:attribute name="version" type="xs:string" use="optional" />
    </xs:complexType>
</xs:element>
</xs:schema>

=== markfinal/BuildAMation/tests/UnicodeTest1/bam/UnicodeTest1.xml
<?xml version="1.0" encoding="utf-8"?>
<PackageDefinition xsi:schemaLocation="http://www.buildamation.com ./Schema/BamPackageDefinitionV1.xsd" name="UnicodeTest1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.buildamation.com">
  <Description>Exercising unicode builds</Description>
  <Dependents>
    <Package name="C" />
    <Package name="MakeFileBuilder" />
    <Package name="Mingw" version="4.8.1" />
    <Package name="NativeBuilder" />
    <Package name="VisualC" version="10.0" />
    <Package name="VisualC" version="11.0" />
    <Package name="VisualC" version="12.0" default="true" />
    <Package name="VisualC" version="14.0" />
    <Package name="VisualC" version="15.0" />
    <Package name="VisualC" version="16" />
    <Package name="VSSolutionBuilder" />
  </Dependents>
  <BamAssemblies>
    <BamAssembly name="Bam.Core" major="2" minor="0" patch="0" />
  </BamAssemblies>
  <DotNetAssemblies>
    <DotNetAssembly name="System" requiredTargetFramework="4.0.30319" />
    <DotNetAssembly name="System.Xml" requiredTargetFramework="4.0.30319" />
    <DotNetAssembly name="System.Core" requiredTargetFramework="4.0.30319" />
  </DotNetAssemblies>
  <SupportedPlatforms>
    <Platform name="Windows" />
  </SupportedPlatforms>
</PackageDefinition>

=== markfinal/BuildAMation/tests/Test8/bam/Test8.xml
<?xml version="1.0" encoding="utf-8"?>
<PackageDefinition xsi:schemaLocation="http://www.buildamation.com ./Schema/BamPackageDefinitionV1.xsd" name="Test8" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.buildamation.com">
  <Dependents>
    <Package name="C" />
    <Package name="Clang" version="Xcode4" />
    <Package name="Clang" version="Xcode5" />
    <Package name="Clang" version="Xcode6" default="true" />
    <Package name="Clang" version="Xcode7" />
    <Package name="Mingw" version="4.8.1" />
    <Package name="Publisher" />
    <Package name="Test7" />
    <Package name="VisualC" version="12.0" />
    <Package name="WindowsSDK" version="8.1" />
  </Dependents>
  <BamAssemblies>
    <BamAssembly name="Bam.Core" major="1" minor="0" />
  </BamAssemblies>
  <DotNetAssemblies>
    <DotNetAssembly name="System" requiredTargetFramework="4.0.30319" />
    <DotNetAssembly name="System.Xml" requiredTargetFramework="4.0.30319" />
    <DotNetAssembly name="System.Core" requiredTargetFramework="4.0.30319" />
  </DotNetAssemblies>
  <SupportedPlatforms>
    <Platform name="Windows" />
    <Platform name="Linux" />
    <Platform name="OSX" />
  </SupportedPlatforms>
</PackageDefinition>

=== markfinal/BuildAMation/tests/MixedTest/bam/MixedTest.xml
<?xml version="1.0" encoding="utf-8"?>
<PackageDefinition xsi:schemaLocation="http://www.buildamation.com ./Schema/BamPackageDefinitionV1.xsd" name="MixedTest" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.buildamation.com">
  <Dependents>
    <Package name="C" />
    <Package name="DotNetFramework" version="3.5" />
    <Package name="Gcc" version="4.8" />
    <Package name="MakeFileBuilder" />
    <Package name="Mingw" version="4.8.1" />
    <Package name="NativeBuilder" />
    <Package name="VisualC" version="12.0" />
    <Package name="VSSolutionBuilder" />
    <Package name="WindowsSDK" version="8.1" />
    <Package name="XcodeBuilder" />
  </Dependents>
  <BamAssemblies>
    <BamAssembly name="Bam.Core" />
  </BamAssemblies>
  <DotNetAssemblies>
    <DotNetAssembly name="System" requiredTargetFramework="4.0.30319" />
    <DotNetAssembly name="System.Xml" requiredTargetFramework="4.0.30319" />
    <DotNetAssembly name="System.Core" requiredTargetFramework="4.0.30319" />
  </DotNetAssemblies>
  <SupportedPlatforms>
    <Platform name="Windows" />
    <Platform name="Linux" />
    <Platform name="OSX" />
  </SupportedPlatforms>
</PackageDefinition>

=== markfinal/BuildAMation/packages/WindowsSDK-7.1/bam/WindowsSDK.xml
<?xml version="1.0" encoding="utf-8"?>
<PackageDefinition xsi:schemaLocation="http://www.buildamation.com ./Schema/BamPackageDefinitionV1.xsd" name="WindowsSDK" version="7.1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.buildamation.com">
  <BamAssemblies>
    <BamAssembly name="Bam.Core" major="1" minor="0" />
  </BamAssemblies>
  <DotNetAssemblies>
    <DotNetAssembly name="System" requiredTargetFramework="4.0.30319" />
    <DotNetAssembly name="System.Xml" requiredTargetFramework="4.0.30319" />
    <DotNetAssembly name="System.Core" requiredTargetFramework="4.0.30319" />
  </DotNetAssemblies>
  <SupportedPlatforms>
    <Platform name="Windows" />
    <Platform name="Linux" />
    <Platform name="OSX" />
  </SupportedPlatforms>
</PackageDefinition>

=== markfinal/BuildAMation/tests/Test5/bam/Test5.xml
<?xml version="1.0" encoding="utf-8"?>
<PackageDefinition xsi:schemaLocation="http://www.buildamation.com ./Schema/BamPackageDefinitionV1.xsd" name="Test5" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.buildamation.com">
  <Description>Link a static and dynamic library into an application.</Description>
  <Dependents>
    <Package name="C" />
    <Package name="Clang" version="Xcode4" />
    <Package name="Clang" version="Xcode5" />
    <Package name="Clang" version="Xcode6" default="true" />
    <Package name="Clang" version="Xcode7" />
    <Package name="Gcc" version="4.8" />
    <Package name="Mingw" version="4.8.1" />
    <Package name="Publisher" />
    <Package name="Test4" />
    <Package name="VisualC" version="12.0" default="true" />
    <Package name="VisualC" version="14.0" />
    <Package name="XcodeBuilder" />
  </Dependents>
  <BamAssemblies>
    <BamAssembly name="Bam.Core" major="1" minor="0" />
  </BamAssemblies>
  <DotNetAssemblies>
    <DotNetAssembly name="System" requiredTargetFramework="4.0.30319" />
    <DotNetAssembly name="System.Xml" requiredTargetFramework="4.0.30319" />
    <DotNetAssembly name="System.Core" requiredTargetFramework="4.0.30319" />
  </DotNetAssemblies>
  <SupportedPlatforms>
    <Platform name="Windows" />
    <Platform name="Linux" />
    <Platform name="OSX" />
  </SupportedPlatforms>
</PackageDefinition>

=== markfinal/BuildAMation/testpackages/OpenCLTest1/bam/OpenCLTest1.xml
<?xml version="1.0" encoding="utf-8"?>
<PackageDefinition name="OpenCLTest1" xsi:schemaLocation="http://www.buildamation.com ./Schema/BamPackageDefinitionV1.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.buildamation.com">
  <Dependents>
    <Package name="AMDAPPSDK" version="2.9" />
    <Package name="C" />
    <Package name="Clang" version="3.1" />
    <Package name="LLVMGcc" version="4.2" />
    <Package name="MakeFileBuilder" />
    <Package name="NativeBuilder" />
    <Package name="Publisher" />
    <Package name="VisualC" version="12.0" />
    <Package name="VSSolutionBuilder" />
    <Package name="WindowsSDK" version="8.1" />
    <Package name="XcodeBuilder" />
  </Dependents>
  <BamAssemblies>
    <BamAssembly name="Bam.Core" />
  </BamAssemblies>
  <DotNetAssemblies>
    <DotNetAssembly name="System" requiredTargetFramework="4.0.30319" />
    <DotNetAssembly name="System.Xml" requiredTargetFramework="4.0.30319" />
    <DotNetAssembly name="System.Core" requiredTargetFramework="4.0.30319" />
  </DotNetAssemblies>
  <SupportedPlatforms>
    <Platform name="Windows" />
    <Platform name="Linux" />
    <Platform name="OSX" />
  </SupportedPlatforms>
  <Definitions>
    <Definition name="USINGAMD" />
  </Definitions>
</PackageDefinition>

=== markfinal/BuildAMation/packages/C/bam/C.xml
<?xml version="1.0" encoding="utf-8"?>
<PackageDefinition xsi:schemaLocation="http://www.buildamation.com ./Schema/BamPackageDefinitionV1.xsd" name="C" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.buildamation.com">
  <Description>Compilers, linkers, archivers, applications, dynamic and static libraries - all for C, C++, ObjectiveC and ObjectiveC++.</Description>
  <Dependents>
    <Package name="CommandLineProcessor" />
  </Dependents>
  <BamAssemblies>
    <BamAssembly name="Bam.Core" major="2" minor="0" patch="0" />
  </BamAssemblies>
  <DotNetAssemblies>
    <DotNetAssembly name="System" requiredTargetFramework="4.0.30319" />
    <DotNetAssembly name="System.Xml" requiredTargetFramework="4.0.30319" />
    <DotNetAssembly name="System.Core" requiredTargetFramework="4.0.30319" />
  </DotNetAssemblies>
  <NuGetPackages>
    <NuGetPackage id="Mono.Posix.NETStandard" version="1.0.0">
      <Platform name="Linux" />
    </NuGetPackage>
  </NuGetPackages>
  <SupportedPlatforms>
    <Platform name="Windows" />
    <Platform name="Linux" />
    <Platform name="OSX" />
  </SupportedPlatforms>
</PackageDefinition>

=== markfinal/BuildAMation/packages/Installer/bam/Installer.xml
<?xml version="1.0" encoding="utf-8"?>
<PackageDefinition xsi:schemaLocation="http://www.buildamation.com ./Schema/BamPackageDefinitionV1.xsd" name="Installer" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.buildamation.com">
  <Description>Support for generating installers, from InnoSetup, NSIS, OSX disk images, zip and tar archives</Description>
  <Dependents>
    <Package name="Publisher" />
  </Dependents>
  <BamAssemblies>
    <BamAssembly name="Bam.Core" major="2" minor="0" patch="0" />
  </BamAssemblies>
  <DotNetAssemblies>
    <DotNetAssembly name="System" requiredTargetFramework="4.0.30319" />
    <DotNetAssembly name="System.Xml" requiredTargetFramework="4.0.30319" />
    <DotNetAssembly name="System.Core" requiredTargetFramework="4.0.30319" />
  </DotNetAssemblies>
  <NuGetPackages>
    <NuGetPackage id="innosetup" version="5.6.1">
      <Platform name="Windows" />
    </NuGetPackage>
    <NuGetPackage id="NSIS" version="2.51.0">
      <Platform name="Windows" />
    </NuGetPackage>
    <NuGetPackage id="7-Zip.CommandLine" version="18.1.0">
      <Platform name="Windows" />
    </NuGetPackage>
  </NuGetPackages>
  <SupportedPlatforms>
    <Platform name="Windows" />
    <Platform name="Linux" />
    <Platform name="OSX" />
  </SupportedPlatforms>
</PackageDefinition>
