=== markfinal/BuildAMation/Bam.Core/Schema/BamPackageDefinitionV1.xsd
<?xml version="1.0" encoding="utf-8" ?>
<xs:schema
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
    targetNamespace="http://www.buildamation.com"
    xmlns="http://www.buildamation.com"
    elementFormDefault="qualified">

<xs:complexType name="bam-assemblies-type">
    <xs:sequence>
        <xs:element name="BamAssembly" minOccurs="1" maxOccurs="unbounded">
            <xs:complexType>
                <xs:attribute name="name" type="xs:string" use="required" />
                <xs:attribute name="major" type="xs:positiveInteger" use="optional" />
                <xs:attribute name="minor" type="xs:nonNegativeInteger" use="optional" />
                <xs:attribute name="patch" type="xs:nonNegativeInteger" use="optional" />
            </xs:complexType>
        </xs:element>
    </xs:sequence>
</xs:complexType>

<xs:complexType name="dotnet-assemblies-type">
    <xs:sequence>
        <xs:element name="DotNetAssembly" minOccurs="1" maxOccurs="unbounded">
            <xs:complexType>
                <xs:attribute name="name" type="xs:string" use="required" />
                <xs:attribute name="requiredTargetFramework" type="xs:string" use="optional" />
            </xs:complexType>
        </xs:element>
    </xs:sequence>
</xs:complexType>

<xs:complexType name="definitions-type">
    <xs:sequence>
        <xs:element name="Definition" minOccurs="1" maxOccurs="unbounded">
            <xs:complexType>
                <xs:attribute name="name" type="xs:string" use="required" />
            </xs:complexType>
        </xs:element>
    </xs:sequence>
</xs:complexType>

<xs:simpleType name="platform-type">
  <xs:restriction base="xs:string">
    <xs:enumeration value="Windows" />
    <xs:enumeration value="Linux" />
    <xs:enumeration value="OSX" />
  </xs:restriction>
</xs:simpleType>

<xs:complexType name="supported-platforms-type">
    <xs:sequence>
        <xs:element name="Platform" minOccurs="1" maxOccurs="unbounded">
            <xs:complexType>
                <xs:attribute name="name" type="platform-type" use="required" />
            </xs:complexType>
        </xs:element>
    </xs:sequence>
</xs:complexType>

<xs:complexType name="package-repository-type">
    <xs:choice minOccurs="1" maxOccurs="unbounded">
        <xs:element name="Repo">
            <xs:complexType>
                <xs:attribute name="dir" type="xs:string" use="required" />
            </xs:complexType>
        </xs:element>
        <xs:element name="NamedRepo">
            <xs:complexType>
              <xs:attribute name="name" type="xs:string" use="required" />
            </xs:complexType>
        </xs:element>
    </xs:choice>
</xs:complexType>

<xs:attributeGroup name="package-attributes">
  <xs:attribute name="name" type="xs:string" use="required" />
  <xs:attribute name="version" type="xs:string" use="optional" />
  <xs:attribute name="default" type="xs:boolean" use="optional" />
</xs:attributeGroup>

<xs:complexType name="package-package-type">
  <xs:attributeGroup ref="package-attributes" />
</xs:complexType>

<xs:complexType name="dependents-type">
  <xs:sequence>
    <xs:element name="Package" minOccurs="1" maxOccurs="unbounded" type="package-package-type" />
  </xs:sequence>
</xs:complexType>

<xs:complexType name="nuget-packages-type">
  <xs:sequence>
    <xs:element name="NuGetPackage" minOccurs="1" maxOccurs="unbounded">
      <xs:complexType>
        <xs:sequence>
          <xs:element name="Platform" minOccurs="1" maxOccurs="unbounded">
            <xs:complexType>
              <xs:attribute name="name" type="platform-type" use="required" />
            </xs:complexType>
          </xs:element>
        </xs:sequence>
        <xs:attribute name="id" type="xs:string" use="required" />
        <xs:attribute name="version" type="xs:string" use="required" />
      </xs:complexType>
    </xs:element>
  </xs:sequence>
</xs:complexType>

<xs:simpleType name="source-valid-type">
  <xs:restriction base="xs:string">
    <xs:enumeration value="http" />
  </xs:restriction>
</xs:simpleType>

<xs:complexType name="sources-type">
  <xs:sequence>
    <xs:element name="Source" minOccurs="1" maxOccurs="unbounded">
      <xs:complexType>
        <xs:attribute name="type" type="source-valid-type" use="required" />
        <xs:attribute name="path" type="xs:anyURI" use="required" />
        <xs:attribute name="subdir" type="xs:string" use="optional" />
        <xs:attribute name="platform" type="platform-type" use="optional" />
      </xs:complexType>
    </xs:element>
  </xs:sequence>
  <xs:attribute name="extractto" type="xs:string" use="optional" />
</xs:complexType>

<!-- root node -->
<xs:element name="PackageDefinition">
    <xs:complexType>
        <xs:all>
            <xs:element name="Description" type="xs:string" minOccurs="0" maxOccurs="1" />
            <xs:element name="Dependents" type="dependents-type" minOccurs="0" maxOccurs="1" />
            <xs:element name="PackageRepositories" type="package-repository-type" minOccurs="0" maxOccurs="1" />
            <xs:element name="BamAssemblies" type="bam-assemblies-type" minOccurs="0" maxOccurs="1" />
            <xs:element name="DotNetAssemblies" type="dotnet-assemblies-type" minOccurs="0" maxOccurs="1" />
            <xs:element name="SupportedPlatforms" type="supported-platforms-type" minOccurs="0" maxOccurs="1" />
            <xs:element name="Definitions" type="definitions-type" minOccurs="0" maxOccurs="1" />
            <xs:element name="NuGetPackages" type="nuget-packages-type" minOccurs="0" maxOccurs="1" />
            <xs:element name="Sources" type="sources-type" minOccurs="0" maxOccurs="1" />
        </xs:all>
        <xs:attribute name="name" type="xs:string" use="required" />
        <xs:attribute name="version" type="xs:string" use="optional" />
    </xs:complexType>
</xs:element>
</xs:schema>

=== markfinal/BuildAMation/packages/VisualC-14.0/bam/VisualC.xml
<?xml version="1.0" encoding="utf-8"?>
<PackageDefinition xsi:schemaLocation="http://www.buildamation.com ./Schema/BamPackageDefinitionV1.xsd" name="VisualC" version="14.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.buildamation.com">
  <Description>Microsoft VisualC 2015 support (Community edition)</Description>
  <Dependents>
    <Package name="VisualCCommon" />
    <Package name="WindowsSDK" version="10" />
  </Dependents>
  <BamAssemblies>
    <BamAssembly name="Bam.Core" major="2" minor="0" patch="0" />
  </BamAssemblies>
  <DotNetAssemblies>
    <DotNetAssembly name="System" requiredTargetFramework="4.0.30319" />
    <DotNetAssembly name="System.Xml" requiredTargetFramework="4.0.30319" />
    <DotNetAssembly name="System.Core" requiredTargetFramework="4.0.30319" />
  </DotNetAssemblies>
  <SupportedPlatforms>
    <Platform name="Windows" />
    <Platform name="Linux" />
    <Platform name="OSX" />
  </SupportedPlatforms>
</PackageDefinition>

=== markfinal/BuildAMation/tests/PublishingTest2/bam/PublishingTest2.xml
<?xml version="1.0" encoding="utf-8"?>
<PackageDefinition xsi:schemaLocation="http://www.buildamation.com ./Schema/BamPackageDefinitionV1.xsd" name="PublishingTest2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.buildamation.com">
  <Description>Publishing test, collating files that are prebuilt</Description>
  <Dependents>
    <Package name="C" />
    <Package name="MakeFileBuilder" />
    <Package name="NativeBuilder" />
    <Package name="Publisher" />
  </Dependents>
  <BamAssemblies>
    <BamAssembly name="Bam.Core" major="1" minor="2" patch="0" />
  </BamAssemblies>
  <DotNetAssemblies>
    <DotNetAssembly name="System" requiredTargetFramework="4.0.30319" />
    <DotNetAssembly name="System.Xml" requiredTargetFramework="4.0.30319" />
    <DotNetAssembly name="System.Core" requiredTargetFramework="4.0.30319" />
  </DotNetAssemblies>
  <SupportedPlatforms>
    <Platform name="Windows" />
    <Platform name="Linux" />
    <Platform name="OSX" />
  </SupportedPlatforms>
</PackageDefinition>

=== markfinal/BuildAMation/tests/MultiBitDepthModuleTest/bam/MultiBitDepthModuleTest.xml
<?xml version="1.0" encoding="utf-8"?>
<PackageDefinition xsi:schemaLocation="http://www.buildamation.com ./Schema/BamPackageDefinitionV1.xsd" name="MultiBitDepthModuleTest" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.buildamation.com">
  <Description>A new package called MultiBitDepthModuleTest</Description>
  <Dependents>
    <Package name="C" />
    <Package name="Gcc" version="4.8" />
    <Package name="NativeBuilder" />
    <Package name="VisualC" version="12.0" />
    <Package name="VSSolutionBuilder" />
  </Dependents>
  <BamAssemblies>
    <BamAssembly name="Bam.Core" major="1" minor="0" />
  </BamAssemblies>
  <DotNetAssemblies>
    <DotNetAssembly name="System" requiredTargetFramework="4.0.30319" />
    <DotNetAssembly name="System.Xml" requiredTargetFramework="4.0.30319" />
    <DotNetAssembly name="System.Core" requiredTargetFramework="4.0.30319" />
  </DotNetAssemblies>
  <SupportedPlatforms>
    <Platform name="Windows" />
    <Platform name="Linux" />
    <Platform name="OSX" />
  </SupportedPlatforms>
</PackageDefinition>

=== markfinal/BuildAMation/packages/Clang-Xcode5/bam/Clang.xml
<?xml version="1.0" encoding="utf-8"?>
<PackageDefinition xsi:schemaLocation="http://www.buildamation.com ./Schema/BamPackageDefinitionV1.xsd" name="Clang" version="Xcode5" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.buildamation.com">
  <Description>Clang support for Xcode5, SDK 10.8 and 10.9</Description>
  <Dependents>
    <Package name="ClangCommon" />
    <Package name="XcodeBuilder" />
  </Dependents>
  <BamAssemblies>
    <BamAssembly name="Bam.Core" major="2" minor="0" patch="0" />
  </BamAssemblies>
  <DotNetAssemblies>
    <DotNetAssembly name="System" requiredTargetFramework="4.0.30319" />
    <DotNetAssembly name="System.Xml" requiredTargetFramework="4.0.30319" />
    <DotNetAssembly name="System.Core" requiredTargetFramework="4.0.30319" />
  </DotNetAssemblies>
  <SupportedPlatforms>
    <Platform name="Windows" />
    <Platform name="Linux" />
    <Platform name="OSX" />
  </SupportedPlatforms>
</PackageDefinition>

=== markfinal/BuildAMation/packages/Publisher/bam/Publisher.xml
<?xml version="1.0" encoding="utf-8"?>
<PackageDefinition xsi:schemaLocation="http://www.buildamation.com ./Schema/BamPackageDefinitionV1.xsd" name="Publisher" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.buildamation.com">
  <Description>Publish built files into runnable distributions, extract debug symbols, and strip binaries.</Description>
  <Dependents>
    <Package name="C" />
  </Dependents>
  <BamAssemblies>
    <BamAssembly name="Bam.Core" major="2" minor="0" patch="0" />
  </BamAssemblies>
  <DotNetAssemblies>
    <DotNetAssembly name="System" requiredTargetFramework="4.0.30319" />
    <DotNetAssembly name="System.Xml" requiredTargetFramework="4.0.30319" />
    <DotNetAssembly name="System.Core" requiredTargetFramework="4.0.30319" />
  </DotNetAssemblies>
  <SupportedPlatforms>
    <Platform name="Windows" />
    <Platform name="Linux" />
    <Platform name="OSX" />
  </SupportedPlatforms>
</PackageDefinition>

=== markfinal/BuildAMation/packages/glew-1.5.7/bam/GLEW.xml
<?xml version="1.0" encoding="utf-8"?>
<PackageDefinition xsi:schemaLocation="http://www.buildamation.com ./Schema/BamPackageDefinitionV1.xsd" name="glew" version="1.5.7" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.buildamation.com">
  <Dependents>
    <Package name="OpenGLSDK" />
  </Dependents>
  <BamAssemblies>
    <BamAssembly name="Bam.Core" />
  </BamAssemblies>
  <DotNetAssemblies>
    <DotNetAssembly name="System" requiredTargetFramework="4.0.30319" />
    <DotNetAssembly name="System.Xml" requiredTargetFramework="4.0.30319" />
    <DotNetAssembly name="System.Core" requiredTargetFramework="4.0.30319" />
  </DotNetAssemblies>
  <SupportedPlatforms>
    <Platform name="Windows" />
    <Platform name="Linux" />
    <Platform name="OSX" />
  </SupportedPlatforms>
</PackageDefinition>

=== markfinal/BuildAMation/packages/OpenGLSDK/bam/OpenGLSDK.xml
<?xml version="1.0" encoding="utf-8"?>
<PackageDefinition xsi:schemaLocation="http://www.buildamation.com ./Schema/BamPackageDefinitionV1.xsd" name="OpenGLSDK" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.buildamation.com">
  <Dependents>
    <Package name="C" />
    <Package name="WindowsSDK" version="8.1" />
  </Dependents>
  <BamAssemblies>
    <BamAssembly name="Bam.Core" />
  </BamAssemblies>
  <DotNetAssemblies>
    <DotNetAssembly name="System" requiredTargetFramework="4.0.30319" />
    <DotNetAssembly name="System.Xml" requiredTargetFramework="4.0.30319" />
    <DotNetAssembly name="System.Core" requiredTargetFramework="4.0.30319" />
  </DotNetAssemblies>
  <SupportedPlatforms>
    <Platform name="Windows" />
    <Platform name="Linux" />
    <Platform name="OSX" />
  </SupportedPlatforms>
</PackageDefinition>

=== markfinal/BuildAMation/tests/PublishingTest1/bam/PublishingTest1.xml
<?xml version="1.0" encoding="utf-8"?>
<PackageDefinition xsi:schemaLocation="http://www.buildamation.com ./Schema/BamPackageDefinitionV1.xsd" name="PublishingTest1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.buildamation.com">
  <Description>A new package called PublishingTest1</Description>
  <Dependents>
    <Package name="C" />
    <Package name="Clang" version="Xcode6" />
    <Package name="Gcc" version="4.8" />
    <Package name="NativeBuilder" />
    <Package name="Publisher" />
    <Package name="VisualC" version="12.0" />
    <Package name="VSSolutionBuilder" />
    <Package name="XcodeBuilder" />
  </Dependents>
  <BamAssemblies>
    <BamAssembly name="Bam.Core" major="1" minor="0" />
  </BamAssemblies>
  <DotNetAssemblies>
    <DotNetAssembly name="System" requiredTargetFramework="4.0.30319" />
    <DotNetAssembly name="System.Xml" requiredTargetFramework="4.0.30319" />
    <DotNetAssembly name="System.Core" requiredTargetFramework="4.0.30319" />
  </DotNetAssemblies>
  <SupportedPlatforms>
    <Platform name="Windows" />
    <Platform name="Linux" />
    <Platform name="OSX" />
  </SupportedPlatforms>
</PackageDefinition>
