=== markfinal/BuildAMation/Bam.Core/Schema/BamPackageDefinitionV1.xsd
<?xml version="1.0" encoding="utf-8" ?>
<xs:schema
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
    targetNamespace="http://www.buildamation.com"
    xmlns="http://www.buildamation.com"
    elementFormDefault="qualified">

<xs:complexType name="bam-assemblies-type">
    <xs:sequence>
        <xs:element name="BamAssembly" minOccurs="1" maxOccurs="unbounded">
            <xs:complexType>
                <xs:attribute name="name" type="xs:string" use="required" />
                <xs:attribute name="major" type="xs:positiveInteger" use="optional" />
                <xs:attribute name="minor" type="xs:nonNegativeInteger" use="optional" />
                <xs:attribute name="patch" type="xs:nonNegativeInteger" use="optional" />
            </xs:complexType>
        </xs:element>
    </xs:sequence>
</xs:complexType>

<xs:complexType name="dotnet-assemblies-type">
    <xs:sequence>
        <xs:element name="DotNetAssembly" minOccurs="1" maxOccurs="unbounded">
            <xs:complexType>
                <xs:attribute name="name" type="xs:string" use="required" />
                <xs:attribute name="requiredTargetFramework" type="xs:string" use="optional" />
            </xs:complexType>
        </xs:element>
    </xs:sequence>
</xs:complexType>

<xs:complexType name="definitions-type">
    <xs:sequence>
        <xs:element name="Definition" minOccurs="1" maxOccurs="unbounded">
            <xs:complexType>
                <xs:attribute name="name" type="xs:string" use="required" />
            </xs:complexType>
        </xs:element>
    </xs:sequence>
</xs:complexType>

<xs:simpleType name="platform-type">
  <xs:restriction base="xs:string">
    <xs:enumeration value="Windows" />
    <xs:enumeration value="Linux" />
    <xs:enumeration value="OSX" />
  </xs:restriction>
</xs:simpleType>

<xs:complexType name="supported-platforms-type">
    <xs:sequence>
        <xs:element name="Platform" minOccurs="1" maxOccurs="unbounded">
            <xs:complexType>
                <xs:attribute name="name" type="platform-type" use="required" />
            </xs:complexType>
        </xs:element>
    </xs:sequence>
</xs:complexType>

<xs:complexType name="package-repository-type">
    <xs:choice minOccurs="1" maxOccurs="unbounded">
        <xs:element name="Repo">
            <xs:complexType>
                <xs:attribute name="dir" type="xs:string" use="required" />
            </xs:complexType>
        </xs:element>
        <xs:element name="NamedRepo">
            <xs:complexType>
              <xs:attribute name="name" type="xs:string" use="required" />
            </xs:complexType>
        </xs:element>
    </xs:choice>
</xs:complexType>

<xs:attributeGroup name="package-attributes">
  <xs:attribute name="name" type="xs:string" use="required" />
  <xs:attribute name="version" type="xs:string" use="optional" />
  <xs:attribute name="default" type="xs:boolean" use="optional" />
</xs:attributeGroup>

<xs:complexType name="package-package-type">
  <xs:attributeGroup ref="package-attributes" />
</xs:complexType>

<xs:complexType name="dependents-type">
  <xs:sequence>
    <xs:element name="Package" minOccurs="1" maxOccurs="unbounded" type="package-package-type" />
  </xs:sequence>
</xs:complexType>

<xs:complexType name="nuget-packages-type">
  <xs:sequence>
    <xs:element name="NuGetPackage" minOccurs="1" maxOccurs="unbounded">
      <xs:complexType>
        <xs:sequence>
          <xs:element name="Platform" minOccurs="1" maxOccurs="unbounded">
            <xs:complexType>
              <xs:attribute name="name" type="platform-type" use="required" />
            </xs:complexType>
          </xs:element>
        </xs:sequence>
        <xs:attribute name="id" type="xs:string" use="required" />
        <xs:attribute name="version" type="xs:string" use="required" />
      </xs:complexType>
    </xs:element>
  </xs:sequence>
</xs:complexType>

<xs:simpleType name="source-valid-type">
  <xs:restriction base="xs:string">
    <xs:enumeration value="http" />
  </xs:restriction>
</xs:simpleType>

<xs:complexType name="sources-type">
  <xs:sequence>
    <xs:element name="Source" minOccurs="1" maxOccurs="unbounded">
      <xs:complexType>
        <xs:attribute name="type" type="source-valid-type" use="required" />
        <xs:attribute name="path" type="xs:anyURI" use="required" />
        <xs:attribute name="subdir" type="xs:string" use="optional" />
        <xs:attribute name="platform" type="platform-type" use="optional" />
      </xs:complexType>
    </xs:element>
  </xs:sequence>
  <xs:attribute name="extractto" type="xs:string" use="optional" />
</xs:complexType>

<!-- root node -->
<xs:element name="PackageDefinition">
    <xs:complexType>
        <xs:all>
            <xs:element name="Description" type="xs:string" minOccurs="0" maxOccurs="1" />
            <xs:element name="Dependents" type="dependents-type" minOccurs="0" maxOccurs="1" />
            <xs:element name="PackageRepositories" type="package-repository-type" minOccurs="0" maxOccurs="1" />
            <xs:element name="BamAssemblies" type="bam-assemblies-type" minOccurs="0" maxOccurs="1" />
            <xs:element name="DotNetAssemblies" type="dotnet-assemblies-type" minOccurs="0" maxOccurs="1" />
            <xs:element name="SupportedPlatforms" type="supported-platforms-type" minOccurs="0" maxOccurs="1" />
            <xs:element name="Definitions" type="definitions-type" minOccurs="0" maxOccurs="1" />
            <xs:element name="NuGetPackages" type="nuget-packages-type" minOccurs="0" maxOccurs="1" />
            <xs:element name="Sources" type="sources-type" minOccurs="0" maxOccurs="1" />
        </xs:all>
        <xs:attribute name="name" type="xs:string" use="required" />
        <xs:attribute name="version" type="xs:string" use="optional" />
    </xs:complexType>
</xs:element>
</xs:schema>

=== markfinal/BuildAMation/packages/Mingw-4.5.0/bam/Mingw.xml
<?xml version="1.0" encoding="utf-8"?>
<PackageDefinition xsi:schemaLocation="http://www.buildamation.com ./Schema/BamPackageDefinitionV1.xsd" name="Mingw" version="4.5.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.buildamation.com">
  <Dependents>
    <Package name="MingwCommon" />
  </Dependents>
  <BamAssemblies>
    <BamAssembly name="Bam.Core" major="2" minor="0" patch="0" />
  </BamAssemblies>
  <DotNetAssemblies>
    <DotNetAssembly name="System" requiredTargetFramework="4.0.30319" />
    <DotNetAssembly name="System.Xml" requiredTargetFramework="4.0.30319" />
    <DotNetAssembly name="System.Core" requiredTargetFramework="4.0.30319" />
  </DotNetAssemblies>
  <SupportedPlatforms>
    <Platform name="Windows" />
    <Platform name="Linux" />
    <Platform name="OSX" />
  </SupportedPlatforms>
</PackageDefinition>

=== markfinal/BuildAMation/packages/Gcc-4.4/bam/Gcc.xml
<?xml version="1.0" encoding="utf-8"?>
<PackageDefinition name="Gcc" version="4.4" xsi:schemaLocation="http://www.buildamation.com ./Schema/BamPackageDefinitionV1.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.buildamation.com">
  <Dependents>
    <Package name="GccCommon" />
  </Dependents>
  <BamAssemblies>
    <BamAssembly name="Bam.Core" />
  </BamAssemblies>
  <DotNetAssemblies>
    <DotNetAssembly name="System" requiredTargetFramework="4.0.30319" />
    <DotNetAssembly name="System.Xml" requiredTargetFramework="4.0.30319" />
    <DotNetAssembly name="System.Core" requiredTargetFramework="4.0.30319" />
  </DotNetAssemblies>
  <SupportedPlatforms>
    <Platform name="Windows" />
    <Platform name="Linux" />
    <Platform name="OSX" />
  </SupportedPlatforms>
</PackageDefinition>

=== markfinal/BuildAMation/tests/ChangeDefaultSettings/bam/ChangeDefaultSettings.xml
<?xml version="1.0" encoding="utf-8"?>
<PackageDefinition xsi:schemaLocation="http://www.buildamation.com ./Schema/BamPackageDefinitionV1.xsd" name="ChangeDefaultSettings" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.buildamation.com">
  <Description>Exercising Bam.Core.ISitePolicy to change the default settings.</Description>
  <Dependents>
    <Package name="C" />
    <Package name="Clang" version="Xcode4" />
    <Package name="Clang" version="Xcode5" />
    <Package name="Clang" version="Xcode6" default="true" />
    <Package name="Clang" version="Xcode7" />
    <Package name="Gcc" version="4.8" />
    <Package name="MakeFileBuilder" />
    <Package name="Mingw" version="4.8.1" />
    <Package name="NativeBuilder" />
    <Package name="VisualC" version="10.0" />
    <Package name="VisualC" version="11.0" />
    <Package name="VisualC" version="12.0" default="true" />
    <Package name="VisualC" version="14.0" />
    <Package name="VSSolutionBuilder" />
    <Package name="XcodeBuilder" />
  </Dependents>
  <BamAssemblies>
    <BamAssembly name="Bam.Core" major="1" minor="0" patch="3" />
  </BamAssemblies>
  <DotNetAssemblies>
    <DotNetAssembly name="System" requiredTargetFramework="4.0.30319" />
    <DotNetAssembly name="System.Xml" requiredTargetFramework="4.0.30319" />
    <DotNetAssembly name="System.Core" requiredTargetFramework="4.0.30319" />
  </DotNetAssemblies>
  <SupportedPlatforms>
    <Platform name="Windows" />
    <Platform name="Linux" />
    <Platform name="OSX" />
  </SupportedPlatforms>
</PackageDefinition>

=== markfinal/BuildAMation/tests/VersionScriptTest1/bam/VersionScriptTest1.xml
<?xml version="1.0" encoding="utf-8"?>
<PackageDefinition xsi:schemaLocation="http://www.buildamation.com ./Schema/BamPackageDefinitionV1.xsd" name="VersionScriptTest1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.buildamation.com">
  <Description>Use a version script to limit API exposure</Description>
  <Dependents>
    <Package name="C" />
    <Package name="Gcc" version="4.8" default="true" />
    <Package name="Gcc" version="5" />
    <Package name="Gcc" version="7" />
    <Package name="Gcc" version="8" />
    <Package name="Gcc" version="9" />
    <Package name="MakeFileBuilder" />
    <Package name="NativeBuilder" />
    <Package name="Publisher" />
  </Dependents>
  <BamAssemblies>
    <BamAssembly name="Bam.Core" major="2" minor="0" patch="0" />
  </BamAssemblies>
  <DotNetAssemblies>
    <DotNetAssembly name="System" requiredTargetFramework="4.0.30319" />
    <DotNetAssembly name="System.Xml" requiredTargetFramework="4.0.30319" />
    <DotNetAssembly name="System.Core" requiredTargetFramework="4.0.30319" />
  </DotNetAssemblies>
  <SupportedPlatforms>
    <Platform name="Linux" />
  </SupportedPlatforms>
</PackageDefinition>

=== markfinal/BuildAMation/tests/ZipTest1/bam/ZipTest1.xml
<?xml version="1.0" encoding="utf-8"?>
<PackageDefinition xsi:schemaLocation="http://www.buildamation.com ./Schema/BamPackageDefinitionV1.xsd" name="ZipTest1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.buildamation.com">
  <Description>Exercise Publisher's ZipModule</Description>
  <Dependents>
    <Package name="Clang" version="Xcode9" />
    <Package name="MakeFileBuilder" />
    <Package name="NativeBuilder" />
    <Package name="Publisher" />
    <Package name="VisualC" version="14.0" />
    <Package name="VSSolutionBuilder" />
    <Package name="XcodeBuilder" />
  </Dependents>
  <BamAssemblies>
    <BamAssembly name="Bam.Core" major="1" minor="2" />
  </BamAssemblies>
  <DotNetAssemblies>
    <DotNetAssembly name="System" requiredTargetFramework="4.0.30319" />
    <DotNetAssembly name="System.Xml" requiredTargetFramework="4.0.30319" />
    <DotNetAssembly name="System.Core" requiredTargetFramework="4.0.30319" />
  </DotNetAssemblies>
  <SupportedPlatforms>
    <Platform name="Windows" />
    <Platform name="Linux" />
    <Platform name="OSX" />
  </SupportedPlatforms>
</PackageDefinition>

=== markfinal/BuildAMation/tests/CyclicDependenciesTest1/bam/CyclicDependenciesTest1.xml
<?xml version="1.0" encoding="utf-8"?>
<PackageDefinition xsi:schemaLocation="http://www.buildamation.com ./Schema/BamPackageDefinitionV1.xsd" name="CyclicDependenciesTest1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.buildamation.com">
  <Description>A test for cyclic dependencies with explicit Module DependsOn calls.</Description>
  <Dependents>
    <Package name="NativeBuilder" />
  </Dependents>
  <BamAssemblies>
    <BamAssembly name="Bam.Core" major="2" minor="0" patch="0" />
  </BamAssemblies>
  <DotNetAssemblies>
    <DotNetAssembly name="System" requiredTargetFramework="4.0.30319" />
    <DotNetAssembly name="System.Xml" requiredTargetFramework="4.0.30319" />
    <DotNetAssembly name="System.Core" requiredTargetFramework="4.0.30319" />
  </DotNetAssemblies>
  <SupportedPlatforms>
    <Platform name="Windows" />
    <Platform name="Linux" />
    <Platform name="OSX" />
  </SupportedPlatforms>
</PackageDefinition>

=== markfinal/BuildAMation/tests/MixedModeCpp/bam/MixedModeCpp.xml
<?xml version="1.0" encoding="utf-8"?>
<PackageDefinition xsi:schemaLocation="http://www.buildamation.com ./Schema/BamPackageDefinitionV1.xsd" name="MixedModeCpp" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.buildamation.com">
  <Dependents>
    <Package name="C" />
    <Package name="MakeFileBuilder" />
    <Package name="NativeBuilder" />
    <Package name="VisualC" version="12.0" default="true" />
    <Package name="VisualC" version="14.0" />
    <Package name="VSSolutionBuilder" />
    <Package name="XcodeBuilder" />
  </Dependents>
  <BamAssemblies>
    <BamAssembly name="Bam.Core" major="1" minor="0" />
  </BamAssemblies>
  <DotNetAssemblies>
    <DotNetAssembly name="System" requiredTargetFramework="4.0.30319" />
    <DotNetAssembly name="System.Xml" requiredTargetFramework="4.0.30319" />
    <DotNetAssembly name="System.Core" requiredTargetFramework="4.0.30319" />
  </DotNetAssemblies>
  <SupportedPlatforms>
    <Platform name="Windows" />
  </SupportedPlatforms>
</PackageDefinition>

=== markfinal/BuildAMation/packages/MakeFileBuilder/bam/MakeFileBuilder.xml
<?xml version="1.0" encoding="utf-8"?>
<PackageDefinition xsi:schemaLocation="http://www.buildamation.com ./Schema/BamPackageDefinitionV1.xsd" name="MakeFileBuilder" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.buildamation.com">
  <Description>Build mode package for generating MakeFiles</Description>
  <BamAssemblies>
    <BamAssembly name="Bam.Core" major="2" minor="0" patch="0" />
  </BamAssemblies>
  <DotNetAssemblies>
    <DotNetAssembly name="System" requiredTargetFramework="4.0.30319" />
    <DotNetAssembly name="System.Xml" requiredTargetFramework="4.0.30319" />
    <DotNetAssembly name="System.Core" requiredTargetFramework="4.0.30319" />
  </DotNetAssemblies>
  <SupportedPlatforms>
    <Platform name="Windows" />
    <Platform name="Linux" />
    <Platform name="OSX" />
  </SupportedPlatforms>
</PackageDefinition>
